### PR TITLE
[KTC-1938] Update Android Mobile Tests

### PR DESCRIPTION
**Pull request by phu-vuong-katalon**

### CODE REVIEW

**Review by huyennguyen-katalon — APPROVED** [review]

**Comment by anle-kat** [comment]
Why do we change APIDemo.apk? I assume that we won't change it in this update

**Review by anle-kat — COMMENTED** [review]
Why do we change APIDemo.apk? I assume that we won't change it in this update

**Comment by phu-vuong-katalon** [comment]
> Why do we change APIDemo.apk? I assume that we won't change it in this update

Hi a @anle-kat , the old APIDemo.apk is outdated, it is not working correctly with the latest Android versions. It only works with very old Android versions (7 or below).

Therefore, update it to support the latest Android versions using the sample app from Appium. https://www.npmjs.com/package/android-apidemos

**Review by anle-kat — APPROVED** [review]
LGTM

**Pull request merged**
